// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
window.rawPages = [
  {
    "url": "./Architecture_of_scale.html",
    "book": "generative",
    "title": "The Architecture of Scale",
    "description": "How we built the modern LLM from transformer foundations into scalable autoregressive systems.",
    "date": "2026-04-01",
    "chapter": "Autoregressive Models",
    "part": "Large Language Models",
    "keywords": "LLM, transformer, scaling, attention, autoregressive modeling",
    "order": 8,
    "status": "live",
    "readingTime": 40
  },
  {
    "url": "./Eigenvectors.html",
    "book": "linear-algebra",
    "title": "Eigenvectors, Diagonalisation, Spectral Theorem",
    "description": "How to find eigenvectors and eigenvalues, and how to diagonalise matrices",
    "date": "2026-04-07",
    "chapter": "Linear Algebra Foundations",
    "part": "  ",
    "keywords": "eigenvectors, eigenvalues, diagonalisation, spectral theorem, positive-definite-matrices, cholesky factorisation",
    "order": 4,
    "status": "live",
    "readingTime": 11
  },
  {
    "url": "./Fixed-length.html",
    "book": "generative",
    "title": "Fixed-Length Autoregressive Models",
    "description": "From FVSBN to NADE and MADE: how autoregressive density estimators scale from logistic regression to masked neural networks, and why fixed-length assumptions fail for language.",
    "date": "2026-04-09",
    "chapter": "Autoregressive Models",
    "part": "Transformer Foundations",
    "keywords": "autoregressive models, FVSBN, NADE, RNADE, MADE, masked autoencoder, density estimation, fixed-length models, binary vectors, MNIST, variable-length sequences, language modeling",
    "order": 2,
    "status": "draft",
    "readingTime": 15
  },
  {
    "url": "./Null_Space_from_Block_RREF.html",
    "book": "linear-algebra",
    "title": "Null Space from Block RREF",
    "description": "A 4x4 rank 2 matrix example showing how the null space basis appears instantly from the block form [I F] as [-F; I].",
    "date": "2026-04-11",
    "chapter": "The Null Space",
    "part": "Block Matrices and RREF",
    "keywords": "null space, rref, rank 2, block matrix, special solutions, gilbert strang, linear algebra",
    "order": 4,
    "status": "live",
    "readingTime": 2
  },
  {
    "url": "./ai-timeline.html",
    "book": "",
    "title": "ai-timeline",
    "description": "",
    "date": "2026-04-01",
    "chapter": "",
    "part": "Main",
    "keywords": "",
    "order": 999,
    "status": "draft",
    "readingTime": 1
  },
  {
    "url": "./attention.html",
    "book": "generative",
    "title": "Attention and the End of Recurrence",
    "description": "From the seq2seq bottleneck to scaled dot-product attention, self-attention, masking, and multi-head attention—the core ideas that replace recurrence in Transformers.",
    "date": "2026-04-09",
    "chapter": "Autoregressive Models",
    "part": "Transformer Foundations",
    "keywords": "attention, cross-attention, self-attention, masked attention, scaled dot-product attention, multi-head attention, transformer, seq2seq bottleneck, queries keys values, autoregressive decoding",
    "order": 6,
    "status": "draft",
    "readingTime": 16
  },
  {
    "url": "./complete_solution.html",
    "book": "linear-algebra",
    "title": "The Complete Solution:&nbsp;$x = x_{p} + x_{n}$",
    "description": "A deep geometric and computational treatment of solving Ax = b using elimination, particular solutions, null spaces, shifted hyperplanes, and rank-based solution classification.",
    "date": "2026-04-11",
    "chapter": "Solving Linear Systems",
    "part": " ",
    "keywords": "Ax=b, complete solution, particular solution, null space, shifted hyperplane, rank, free variables, linear algebra",
    "order": 8,
    "status": "live",
    "readingTime": 6
  },
  {
    "url": "./counting.html",
    "book": "Stats",
    "title": "Probability and Counting",
    "description": "A complete foundation of probability axioms, sampling, permutations, combinations, and core counting principles.",
    "date": "2026-04-10",
    "chapter": "Stats Foundation",
    "part": " ",
    "keywords": "probability, counting, permutations, combinations, bayes theorem, stars and bars, sample space",
    "order": 1,
    "status": "live",
    "readingTime": 6
  },
  {
    "url": "./dist.html",
    "book": "Stats",
    "title": "Common Probability Distributions",
    "description": "A comprehensive guide to discrete and continuous probability distributions, including PMF, PDF, CDF, means, and variances.",
    "date": "2026-04-10",
    "chapter": "Stats Foundation",
    "part": " ",
    "keywords": "probability, distributions, statistics, normal distribution, binomial, poisson, exponential, PMF, PDF, CDF",
    "order": 4,
    "status": "live",
    "readingTime": 4
  },
  {
    "url": "./intro_ar.html",
    "book": "generative",
    "title": "Intro to Autoregression Models",
    "description": "From exponential joint distributions to tractable autoregressive factorization",
    "date": "2026-04-08",
    "chapter": "Autoregressive Models",
    "part": "Transformer Foundations",
    "keywords": "chain rule, bayesian networks, markov models, generative modeling",
    "order": 1,
    "status": "draft",
    "readingTime": 6
  },
  {
    "url": "./intro_lvm.html",
    "book": "generative",
    "title": "Introduction to Latent Variable Models",
    "description": "The limitations of autoregressive models and the motivation for latent variable models, illustrated through the compass analogy.",
    "date": "2026-04-09",
    "chapter": "Latent Variable Models",
    "part": " ",
    "keywords": "latent variable models, autoregressive models, Bayesian inference",
    "order": 1,
    "status": "draft",
    "readingTime": 2
  },
  {
    "url": "./pos_enc.html",
    "book": "generative",
    "title": "Position Representation",
    "description": "How positions are represented in the same vector space as embeddings using sinusoidal encodings and Rotary Positional Embeddings (RoPE).",
    "date": "2026-04-03",
    "chapter": "Autoregressive Models",
    "part": "Large Language Models",
    "keywords": "positional encoding, RoPE, sinusoidal embeddings, attention, transformer",
    "order": 5,
    "status": "live",
    "readingTime": 8
  },
  {
    "url": "./rnn.html",
    "book": "generative",
    "title": "Recurrent Neural Networks and Sequence Memory",
    "description": "How recurrent neural networks model sequential dependencies, why gradients vanish or explode, and how LSTMs, GRUs, bidirectional networks, and encoder-decoder models address memory limitations.",
    "date": "2026-04-09",
    "chapter": "Autoregressive Models",
    "part": "Transformer Foundations",
    "keywords": "RNN, recurrent neural network, hidden state, BPTT, vanishing gradients, exploding gradients, LSTM, GRU, bidirectional RNN, stacked RNN, seq2seq, encoder decoder, sequence memory, attention bottleneck",
    "order": 5,
    "status": "draft",
    "readingTime": 13
  },
  {
    "url": "./sle.html",
    "book": "linear-algebra",
    "title": "Solving Linear Equations",
    "description": "How to solve linear equations using Gaussian elimination and matrix factorization",
    "date": "2026-04-04",
    "chapter": "Linear Algebra Foundations",
    "part": " ",
    "keywords": "pivot, LU factorization, Gaussian elimination, linear equations, back substitution",
    "order": 2,
    "status": "draft",
    "readingTime": 8
  },
  {
    "url": "./taxonomy.html",
    "book": "generative",
    "title": "Taxonomy of Generative Models",
    "description": "A comprehensive classification of generative AI models, including explicit likelihood, implicit likelihood, and score-based approaches.",
    "date": "2026-04-07",
    "chapter": "Taxonomy",
    "part": "Foundations",
    "keywords": "generative models, taxonomy, autoregressive, normalizing flows, VAE, GAN, diffusion models, score-based models",
    "order": 1,
    "status": "live",
    "readingTime": 1
  },
  {
    "url": "./vec_spaces.html",
    "book": "linear-algebra",
    "title": "Vector Spaces & Subspaces",
    "description": " vector spaces, the column space, the null space, basis, dimension",
    "date": "2026-04-04",
    "chapter": "Linear Algebra Foundations",
    "part": " ",
    "keywords": "vector spaces, subspaces, basis, dimension, rank, nullity, column space, row space, null space",
    "order": 3,
    "status": "live",
    "readingTime": 7
  },
  {
    "url": "./word_rep.html",
    "book": "generative",
    "title": "Word Representation",
    "description": "How words become vectors",
    "date": "2026-04-04",
    "chapter": "Autoregressive Models",
    "part": "Transformer Foundations",
    "keywords": "embeddings, word2vec, skipgram, CBOW",
    "order": 4,
    "status": "draft",
    "readingTime": 13
  }
];
