// AUTO-GENERATED — do not edit
window.rawPages = [
  {
    "url": "../Library/ai/World_models/Jepa/",
    "cleanUrl": "../Library/ai/World_models/Jepa/",
    "sourcePath": "Library/ai/World_models/Jepa/index.html",
    "publicPath": "Library/ai/World_models/Jepa/",
    "cleanPath": "Library/ai/World_models/Jepa/",
    "book": "AI",
    "bookTitle": "AI",
    "bookSlug": "ai",
    "bookOrder": 999,
    "title": "The Predictive Path: JEPA and World Models",
    "description": "Why predicting pixels leads to blur, and how Joint Embedding Predictive Architectures (JEPA) pave the way for true world models.",
    "date": "2026-04-10",
    "section": "World Models",
    "chapter": "Joint Embeddings",
    "chapterOrder": 4,
    "chapterNumber": "4",
    "lessonorder": 1,
    "lessonNumber": "1",
    "part": " ",
    "tier": "core",
    "keywords": "JEPA, world models, latent representations, representation collapse, Barlow Twins, Yann LeCun",
    "status": "draft",
    "readingTime": 5
  },
  {
    "url": "../Library/ai/generative-models/01.autoregressive-models/01.intro-to-autoregression-models/",
    "cleanUrl": "../Library/ai/generative-models/autoregressive-models/intro-to-autoregression-models/",
    "sourcePath": "Library/ai/generative-models/01.autoregressive-models/01.intro-to-autoregression-models/index.html",
    "publicPath": "Library/ai/generative-models/01.autoregressive-models/01.intro-to-autoregression-models/",
    "cleanPath": "Library/ai/generative-models/autoregressive-models/intro-to-autoregression-models/",
    "book": "AI",
    "bookTitle": "AI",
    "bookSlug": "ai",
    "bookOrder": 999,
    "title": "Intro to Autoregression Models",
    "description": "From exponential joint distributions to tractable autoregressive factorization",
    "date": "2026-04-08",
    "section": "Generative Models",
    "chapter": "Autoregressive Models",
    "chapterOrder": 1,
    "chapterNumber": "1",
    "lessonorder": 1,
    "lessonNumber": "1",
    "part": "Transformer Foundations",
    "tier": "core",
    "keywords": "chain rule, bayesian networks, markov models, generative modeling",
    "status": "live",
    "readingTime": 8
  },
  {
    "url": "../Library/ai/generative-models/01.autoregressive-models/02.fixed-length-autoregressive-models/",
    "cleanUrl": "../Library/ai/generative-models/autoregressive-models/fixed-length-autoregressive-models/",
    "sourcePath": "Library/ai/generative-models/01.autoregressive-models/02.fixed-length-autoregressive-models/index.html",
    "publicPath": "Library/ai/generative-models/01.autoregressive-models/02.fixed-length-autoregressive-models/",
    "cleanPath": "Library/ai/generative-models/autoregressive-models/fixed-length-autoregressive-models/",
    "book": "AI",
    "bookTitle": "AI",
    "bookSlug": "ai",
    "bookOrder": 999,
    "title": "Fixed-Length Autoregressive Models",
    "description": "From FVSBN to NADE and MADE: how autoregressive density estimators scale from logistic regression to masked neural networks, and why fixed-length assumptions fail for language.",
    "date": "2026-04-09",
    "section": "Generative Models",
    "chapter": "Autoregressive Models",
    "chapterOrder": 1,
    "chapterNumber": "1",
    "lessonorder": 2,
    "lessonNumber": "2",
    "part": "Transformer Foundations",
    "tier": "core",
    "keywords": "autoregressive models, FVSBN, NADE, RNADE, MADE, masked autoencoder, density estimation, fixed-length models, binary vectors, MNIST, variable-length sequences, language modeling",
    "status": "draft",
    "readingTime": 15
  },
  {
    "url": "../Library/ai/generative-models/01.autoregressive-models/03.word-representation/",
    "cleanUrl": "../Library/ai/generative-models/autoregressive-models/word-representation/",
    "sourcePath": "Library/ai/generative-models/01.autoregressive-models/03.word-representation/index.html",
    "publicPath": "Library/ai/generative-models/01.autoregressive-models/03.word-representation/",
    "cleanPath": "Library/ai/generative-models/autoregressive-models/word-representation/",
    "book": "AI",
    "bookTitle": "AI",
    "bookSlug": "ai",
    "bookOrder": 999,
    "title": "Word Representation",
    "description": "How words become vectors",
    "date": "2026-04-04",
    "section": "Generative Models",
    "chapter": "Autoregressive Models",
    "chapterOrder": 1,
    "chapterNumber": "1",
    "lessonorder": 3,
    "lessonNumber": "3",
    "part": "Transformer Foundations",
    "tier": "core",
    "keywords": "embeddings, word2vec, skipgram, CBOW",
    "status": "draft",
    "readingTime": 13
  },
  {
    "url": "../Library/ai/generative-models/01.autoregressive-models/04.recurrent-neural-networks-and-sequence-memory/",
    "cleanUrl": "../Library/ai/generative-models/autoregressive-models/recurrent-neural-networks-and-sequence-memory/",
    "sourcePath": "Library/ai/generative-models/01.autoregressive-models/04.recurrent-neural-networks-and-sequence-memory/index.html",
    "publicPath": "Library/ai/generative-models/01.autoregressive-models/04.recurrent-neural-networks-and-sequence-memory/",
    "cleanPath": "Library/ai/generative-models/autoregressive-models/recurrent-neural-networks-and-sequence-memory/",
    "book": "AI",
    "bookTitle": "AI",
    "bookSlug": "ai",
    "bookOrder": 999,
    "title": "Recurrent Neural Networks and Sequence Memory",
    "description": "How recurrent neural networks model sequential dependencies, why gradients vanish or explode, and how LSTMs, GRUs, bidirectional networks, and encoder-decoder models address memory limitations.",
    "date": "2026-04-09",
    "section": "Generative Models",
    "chapter": "Autoregressive Models",
    "chapterOrder": 1,
    "chapterNumber": "1",
    "lessonorder": 4,
    "lessonNumber": "4",
    "part": "Transformer Foundations",
    "tier": "core",
    "keywords": "RNN, recurrent neural network, hidden state, BPTT, vanishing gradients, exploding gradients, LSTM, GRU, bidirectional RNN, stacked RNN, seq2seq, encoder decoder, sequence memory, attention bottleneck",
    "status": "draft",
    "readingTime": 13
  },
  {
    "url": "../Library/ai/generative-models/01.autoregressive-models/05.attention-mechanism/",
    "cleanUrl": "../Library/ai/generative-models/autoregressive-models/attention-mechanism/",
    "sourcePath": "Library/ai/generative-models/01.autoregressive-models/05.attention-mechanism/index.html",
    "publicPath": "Library/ai/generative-models/01.autoregressive-models/05.attention-mechanism/",
    "cleanPath": "Library/ai/generative-models/autoregressive-models/attention-mechanism/",
    "book": "AI",
    "bookTitle": "AI",
    "bookSlug": "ai",
    "bookOrder": 999,
    "title": "Attention Mechanism",
    "description": "From the seq2seq bottleneck to scaled dot-product attention, self-attention, masking, and multi-head attention—the core ideas that replace recurrence in Transformers.",
    "date": "2026-04-09",
    "section": "Generative Models",
    "chapter": "Autoregressive Models",
    "chapterOrder": 1,
    "chapterNumber": "1",
    "lessonorder": 5,
    "lessonNumber": "5",
    "part": "Transformer Foundations",
    "tier": "core",
    "keywords": "attention, cross-attention, self-attention, masked attention, scaled dot-product attention, multi-head attention, transformer, seq2seq bottleneck, queries keys values, autoregressive decoding",
    "status": "draft",
    "readingTime": 16
  },
  {
    "url": "../Library/ai/generative-models/01.autoregressive-models/06.the-transformer-architecture/",
    "cleanUrl": "../Library/ai/generative-models/autoregressive-models/the-transformer-architecture/",
    "sourcePath": "Library/ai/generative-models/01.autoregressive-models/06.the-transformer-architecture/index.html",
    "publicPath": "Library/ai/generative-models/01.autoregressive-models/06.the-transformer-architecture/",
    "cleanPath": "Library/ai/generative-models/autoregressive-models/the-transformer-architecture/",
    "book": "AI",
    "bookTitle": "AI",
    "bookSlug": "ai",
    "bookOrder": 999,
    "title": "The Transformer Architecture",
    "description": "From positional encodings and masked self-attention to residual refinement, layer stacking, and autoregressive inference — the complete Transformer architecture built from first principles.",
    "date": "2026-04-22",
    "section": "Generative Models",
    "chapter": "Autoregressive Models",
    "chapterOrder": 1,
    "chapterNumber": "1",
    "lessonorder": 6,
    "lessonNumber": "6",
    "part": "Transformer Foundations",
    "tier": "core",
    "keywords": "transformer, positional encoding, masked self-attention, cross-attention, feed-forward network, residual connections, layer normalization, encoder-decoder, decoder-only, autoregressive, pre-norm, GPT, BERT",
    "status": "draft",
    "readingTime": 14
  },
  {
    "url": "../Library/ai/generative-models/01.autoregressive-models/07.position-representation/",
    "cleanUrl": "../Library/ai/generative-models/autoregressive-models/position-representation/",
    "sourcePath": "Library/ai/generative-models/01.autoregressive-models/07.position-representation/index.html",
    "publicPath": "Library/ai/generative-models/01.autoregressive-models/07.position-representation/",
    "cleanPath": "Library/ai/generative-models/autoregressive-models/position-representation/",
    "book": "AI",
    "bookTitle": "AI",
    "bookSlug": "ai",
    "bookOrder": 999,
    "title": "Position Representation",
    "description": "How positions are represented in the same vector space as embeddings using sinusoidal encodings and Rotary Positional Embeddings (RoPE).",
    "date": "2026-04-03",
    "section": "Generative Models",
    "chapter": "Autoregressive Models",
    "chapterOrder": 1,
    "chapterNumber": "1",
    "lessonorder": 7,
    "lessonNumber": "7",
    "part": "Transformer Foundations",
    "tier": "core",
    "keywords": "positional encoding, RoPE, sinusoidal embeddings, attention, transformer",
    "status": "live",
    "readingTime": 8
  },
  {
    "url": "../Library/ai/generative-models/01.autoregressive-models/09.attention-approximation/",
    "cleanUrl": "../Library/ai/generative-models/autoregressive-models/attention-approximation/",
    "sourcePath": "Library/ai/generative-models/01.autoregressive-models/09.attention-approximation/index.html",
    "publicPath": "Library/ai/generative-models/01.autoregressive-models/09.attention-approximation/",
    "cleanPath": "Library/ai/generative-models/autoregressive-models/attention-approximation/",
    "book": "AI",
    "bookTitle": "AI",
    "bookSlug": "ai",
    "bookOrder": 999,
    "title": "Attention Approximation",
    "description": "The Cost of Attention and How to Reduce It--From the quadratic bottleneck of full attention to sparse patterns, low-rank decompositions, kernel approximations, IO-aware exact computation, and recurrent hybrids—the landscape of attention approximation.",
    "date": "2026-04-22",
    "section": "Generative Models",
    "chapter": "Autoregressive Models",
    "chapterOrder": 1,
    "chapterNumber": "1",
    "lessonorder": 9,
    "lessonNumber": "9",
    "part": "Transformer Foundations",
    "tier": "core",
    "keywords": "attention approximation, sparse attention, linear attention, Linformer, Performer, FAVOR+, FlashAttention, Mamba, RWKV, BigBird, Longformer, random features, kernel methods, sliding window attention, state space models",
    "status": "draft",
    "readingTime": 22
  },
  {
    "url": "../Library/ai/generative-models/01.autoregressive-models/10.shared-attention/",
    "cleanUrl": "../Library/ai/generative-models/autoregressive-models/shared-attention/",
    "sourcePath": "Library/ai/generative-models/01.autoregressive-models/10.shared-attention/index.html",
    "publicPath": "Library/ai/generative-models/01.autoregressive-models/10.shared-attention/",
    "cleanPath": "Library/ai/generative-models/autoregressive-models/shared-attention/",
    "book": "AI",
    "bookTitle": "AI",
    "bookSlug": "ai",
    "bookOrder": 999,
    "title": "Shared Attention",
    "description": "Multi-Query Attention, Grouped-Query Attention, and Cross-Layer Attention—how sharing key and value projections across heads and layers reduces the KV cache bottleneck at inference time.",
    "date": "2026-04-24",
    "section": "Generative Models",
    "chapter": "Autoregressive Models",
    "chapterOrder": 1,
    "chapterNumber": "1",
    "lessonorder": 10,
    "lessonNumber": "10",
    "part": "Transformer Foundations",
    "tier": "core",
    "keywords": "shared attention, multi-query attention, grouped-query attention, cross-layer attention, KV cache, inference efficiency, MQA, GQA, CLA, key-value sharing, attention heads, Transformer",
    "status": "draft",
    "readingTime": 12
  },
  {
    "url": "../Library/ai/generative-models/01.autoregressive-models/15.the-architecture-of-scale/",
    "cleanUrl": "../Library/ai/generative-models/autoregressive-models/the-architecture-of-scale/",
    "sourcePath": "Library/ai/generative-models/01.autoregressive-models/15.the-architecture-of-scale/index.html",
    "publicPath": "Library/ai/generative-models/01.autoregressive-models/15.the-architecture-of-scale/",
    "cleanPath": "Library/ai/generative-models/autoregressive-models/the-architecture-of-scale/",
    "book": "AI",
    "bookTitle": "AI",
    "bookSlug": "ai",
    "bookOrder": 999,
    "title": "The Architecture of Scale",
    "description": "How we built the modern LLM from transformer foundations into scalable autoregressive systems.",
    "date": "2026-04-01",
    "section": "Generative Models",
    "chapter": "Autoregressive Models",
    "chapterOrder": 1,
    "chapterNumber": "1",
    "lessonorder": 15,
    "lessonNumber": "15",
    "part": "Large Language Models",
    "tier": "deep-dive",
    "keywords": "LLM, transformer, scaling, attention, autoregressive modeling",
    "status": "live",
    "readingTime": 40
  },
  {
    "url": "../Library/ai/generative-models/02.latent-variable-models/01.introduction-to-latent-variable-models/",
    "cleanUrl": "../Library/ai/generative-models/latent-variable-models/introduction-to-latent-variable-models/",
    "sourcePath": "Library/ai/generative-models/02.latent-variable-models/01.introduction-to-latent-variable-models/index.html",
    "publicPath": "Library/ai/generative-models/02.latent-variable-models/01.introduction-to-latent-variable-models/",
    "cleanPath": "Library/ai/generative-models/latent-variable-models/introduction-to-latent-variable-models/",
    "book": "AI",
    "bookTitle": "AI",
    "bookSlug": "ai",
    "bookOrder": 999,
    "title": "Introduction to Latent Variable Models",
    "description": "The limitations of autoregressive models and the motivation for latent variable models, illustrated through the compass analogy.",
    "date": "2026-04-09",
    "section": "Generative Models",
    "chapter": "Latent Variable Models",
    "chapterOrder": 2,
    "chapterNumber": "2",
    "lessonorder": 1,
    "lessonNumber": "1",
    "part": " ",
    "tier": "core",
    "keywords": "latent variable models, autoregressive models, Bayesian inference",
    "status": "draft",
    "readingTime": 2
  },
  {
    "url": "../Library/ai/generative-models/10.Landscape/01.taxonomy-of-generative-models/",
    "cleanUrl": "../Library/ai/generative-models/Landscape/taxonomy-of-generative-models/",
    "sourcePath": "Library/ai/generative-models/10.Landscape/01.taxonomy-of-generative-models/index.html",
    "publicPath": "Library/ai/generative-models/10.Landscape/01.taxonomy-of-generative-models/",
    "cleanPath": "Library/ai/generative-models/Landscape/taxonomy-of-generative-models/",
    "book": "AI",
    "bookTitle": "AI",
    "bookSlug": "ai",
    "bookOrder": 999,
    "title": "Taxonomy of Generative Models",
    "description": "A comprehensive classification of generative AI models, including explicit likelihood, implicit likelihood, and score-based approaches.",
    "date": "2026-04-07",
    "section": "Generative Models",
    "chapter": "Landscape",
    "chapterOrder": 10,
    "chapterNumber": "10",
    "lessonorder": 1,
    "lessonNumber": "1",
    "part": " ",
    "tier": "core",
    "keywords": "generative models, taxonomy, autoregressive, normalizing flows, VAE, GAN, diffusion models, score-based models",
    "status": "live",
    "readingTime": 1
  },
  {
    "url": "../Library/ai/generative-models/10.Landscape/02.ai-evolution-timeline/",
    "cleanUrl": "../Library/ai/generative-models/Landscape/ai-evolution-timeline/",
    "sourcePath": "Library/ai/generative-models/10.Landscape/02.ai-evolution-timeline/index.html",
    "publicPath": "Library/ai/generative-models/10.Landscape/02.ai-evolution-timeline/",
    "cleanPath": "Library/ai/generative-models/Landscape/ai-evolution-timeline/",
    "book": "AI",
    "bookTitle": "AI",
    "bookSlug": "ai",
    "bookOrder": 999,
    "title": "AI Evolution Timeline",
    "description": "",
    "date": "2026-04-01",
    "section": "Generative Models",
    "chapter": "Landscape",
    "chapterOrder": 10,
    "chapterNumber": "10",
    "lessonorder": 2,
    "lessonNumber": "2",
    "part": " ",
    "tier": "core",
    "keywords": "",
    "status": "draft",
    "readingTime": 1
  },
  {
    "url": "../Library/mathematics/linear-algebra/determinants/01.properties/",
    "cleanUrl": "../Library/mathematics/linear-algebra/determinants/properties/",
    "sourcePath": "Library/mathematics/linear-algebra/determinants/01.properties/index.html",
    "publicPath": "Library/mathematics/linear-algebra/determinants/01.properties/",
    "cleanPath": "Library/mathematics/linear-algebra/determinants/properties/",
    "book": "Linear Algebra",
    "bookTitle": "Linear Algebra",
    "bookSlug": "linear-algebra",
    "bookOrder": 999,
    "title": "Properties of Determinants",
    "description": "Understanding the determinant: its core properties, what it tells us about invertibility, how to compute it via elimination, and its connection to area and volume.",
    "date": "2026-04-25",
    "section": "",
    "chapter": "Determinants",
    "chapterOrder": 4,
    "chapterNumber": "4",
    "lessonorder": 1,
    "lessonNumber": "1",
    "part": " ",
    "tier": "core",
    "keywords": "determinant, properties of determinants, invertibility, cofactor, product rule, transpose",
    "status": "draft",
    "readingTime": 22
  },
  {
    "url": "../Library/mathematics/linear-algebra/eigenvalues-and-eigenvectors/01.eigenvectors/",
    "cleanUrl": "../Library/mathematics/linear-algebra/eigenvalues-and-eigenvectors/eigenvectors/",
    "sourcePath": "Library/mathematics/linear-algebra/eigenvalues-and-eigenvectors/01.eigenvectors/index.html",
    "publicPath": "Library/mathematics/linear-algebra/eigenvalues-and-eigenvectors/01.eigenvectors/",
    "cleanPath": "Library/mathematics/linear-algebra/eigenvalues-and-eigenvectors/eigenvectors/",
    "book": "Linear Algebra",
    "bookTitle": "Linear Algebra",
    "bookSlug": "linear-algebra",
    "bookOrder": 999,
    "title": "Eigenvectors",
    "description": "How to find eigenvectors and eigenvalues, and how to diagonalise matrices",
    "date": "2026-04-07",
    "section": "",
    "chapter": "Eigenvalues and Eigenvectors",
    "chapterOrder": 5,
    "chapterNumber": "5",
    "lessonorder": 1,
    "lessonNumber": "1",
    "part": "  ",
    "tier": "core",
    "keywords": "eigenvectors, eigenvalues, diagonalisation, spectral theorem, positive definite matrices, cholesky factorisation",
    "status": "live",
    "readingTime": 11
  },
  {
    "url": "../Library/mathematics/linear-algebra/eigenvalues-and-eigenvectors/02.diagonalisation-spectral-theorem/",
    "cleanUrl": "../Library/mathematics/linear-algebra/eigenvalues-and-eigenvectors/diagonalisation-spectral-theorem/",
    "sourcePath": "Library/mathematics/linear-algebra/eigenvalues-and-eigenvectors/02.diagonalisation-spectral-theorem/index.html",
    "publicPath": "Library/mathematics/linear-algebra/eigenvalues-and-eigenvectors/02.diagonalisation-spectral-theorem/",
    "cleanPath": "Library/mathematics/linear-algebra/eigenvalues-and-eigenvectors/diagonalisation-spectral-theorem/",
    "book": "Linear Algebra",
    "bookTitle": "Linear Algebra",
    "bookSlug": "linear-algebra",
    "bookOrder": 999,
    "title": "Diagonalisation, Spectral Theorem",
    "description": "How to find eigenvectors and eigenvalues, and how to diagonalise matrices",
    "date": "2026-04-07",
    "section": "",
    "chapter": "Eigenvalues and Eigenvectors",
    "chapterOrder": 5,
    "chapterNumber": "5",
    "lessonorder": 2,
    "lessonNumber": "2",
    "part": "  ",
    "tier": "core",
    "keywords": "eigenvectors, eigenvalues, diagonalisation, spectral theorem, positive definite matrices, cholesky factorisation",
    "status": "live",
    "readingTime": 7
  },
  {
    "url": "../Library/mathematics/linear-algebra/eigenvalues-and-eigenvectors/03.positive-defnite-matrices/",
    "cleanUrl": "../Library/mathematics/linear-algebra/eigenvalues-and-eigenvectors/positive-defnite-matrices/",
    "sourcePath": "Library/mathematics/linear-algebra/eigenvalues-and-eigenvectors/03.positive-defnite-matrices/index.html",
    "publicPath": "Library/mathematics/linear-algebra/eigenvalues-and-eigenvectors/03.positive-defnite-matrices/",
    "cleanPath": "Library/mathematics/linear-algebra/eigenvalues-and-eigenvectors/positive-defnite-matrices/",
    "book": "Linear Algebra",
    "bookTitle": "Linear Algebra",
    "bookSlug": "linear-algebra",
    "bookOrder": 999,
    "title": "Positive Defnite Matrices",
    "description": "What positive definite and positive semidefinite matrices are, and given a matrix A, how do you find out if it is positive definite or positive semidefinite?",
    "date": "2026-04-07",
    "section": "",
    "chapter": "Eigenvalues and Eigenvectors",
    "chapterOrder": 5,
    "chapterNumber": "5",
    "lessonorder": 3,
    "lessonNumber": "3",
    "part": "  ",
    "tier": "core",
    "keywords": "positive definite matrices, positive semidefinite matrices, quadratic forms, eigenvalue test, pivot test, Sylvester",
    "status": "live",
    "readingTime": 19
  },
  {
    "url": "../Library/mathematics/linear-algebra/eigenvalues-and-eigenvectors/04.google-search/",
    "cleanUrl": "../Library/mathematics/linear-algebra/eigenvalues-and-eigenvectors/google-search/",
    "sourcePath": "Library/mathematics/linear-algebra/eigenvalues-and-eigenvectors/04.google-search/index.html",
    "publicPath": "Library/mathematics/linear-algebra/eigenvalues-and-eigenvectors/04.google-search/",
    "cleanPath": "Library/mathematics/linear-algebra/eigenvalues-and-eigenvectors/google-search/",
    "book": "Linear Algebra",
    "bookTitle": "Linear Algebra",
    "bookSlug": "linear-algebra",
    "bookOrder": 999,
    "title": "Applications- Google search",
    "description": "How Google",
    "date": "2026-04-07",
    "section": "",
    "chapter": "Eigenvalues and Eigenvectors",
    "chapterOrder": 99,
    "chapterNumber": "99",
    "lessonorder": 4,
    "lessonNumber": "4",
    "part": "  ",
    "tier": "core",
    "keywords": "markov matrix, pagerank, steady state, perron-frobenius, eigenvectors, google, damping factor",
    "status": "live",
    "readingTime": 10
  },
  {
    "url": "../Library/mathematics/linear-algebra/orthogonality-and-projections/01.orthogonality-of-the-four-subspaces/",
    "cleanUrl": "../Library/mathematics/linear-algebra/orthogonality-and-projections/orthogonality-of-the-four-subspaces/",
    "sourcePath": "Library/mathematics/linear-algebra/orthogonality-and-projections/01.orthogonality-of-the-four-subspaces/index.html",
    "publicPath": "Library/mathematics/linear-algebra/orthogonality-and-projections/01.orthogonality-of-the-four-subspaces/",
    "cleanPath": "Library/mathematics/linear-algebra/orthogonality-and-projections/orthogonality-of-the-four-subspaces/",
    "book": "Linear Algebra",
    "bookTitle": "Linear Algebra",
    "bookSlug": "linear-algebra",
    "bookOrder": 999,
    "title": "Orthogonality of the Four Subspaces",
    "description": "A geometric and computational treatment of orthogonal subspaces, orthogonal complements, and the fundamental theorem of linear algebra.",
    "date": "2026-04-18",
    "section": "",
    "chapter": "Orthogonality and Projections",
    "chapterOrder": 3,
    "chapterNumber": "3",
    "lessonorder": 1,
    "lessonNumber": "1",
    "part": " ",
    "tier": "core",
    "keywords": "orthogonality, fundamental subspaces, row space, null space, orthogonal complements, linear algebra",
    "status": "draft",
    "readingTime": 6
  },
  {
    "url": "../Library/mathematics/linear-algebra/orthogonality-and-projections/02.projections-onto-subspaces/",
    "cleanUrl": "../Library/mathematics/linear-algebra/orthogonality-and-projections/projections-onto-subspaces/",
    "sourcePath": "Library/mathematics/linear-algebra/orthogonality-and-projections/02.projections-onto-subspaces/index.html",
    "publicPath": "Library/mathematics/linear-algebra/orthogonality-and-projections/02.projections-onto-subspaces/",
    "cleanPath": "Library/mathematics/linear-algebra/orthogonality-and-projections/projections-onto-subspaces/",
    "book": "Linear Algebra",
    "bookTitle": "Linear Algebra",
    "bookSlug": "linear-algebra",
    "bookOrder": 999,
    "title": "Projections onto Subspaces",
    "description": "Deriving the mathematics of orthogonal projections onto lines and n-dimensional subspaces using the normal equation and projection matrices.",
    "date": "2026-04-18",
    "section": "",
    "chapter": "Orthogonality and Projections",
    "chapterOrder": 3,
    "chapterNumber": "3",
    "lessonorder": 2,
    "lessonNumber": "2",
    "part": " ",
    "tier": "core",
    "keywords": "projections, orthogonal projection, projection matrix, least squares, normal equation, linear algebra",
    "status": "draft",
    "readingTime": 11
  },
  {
    "url": "../Library/mathematics/linear-algebra/orthogonality-and-projections/03.projection-matrices-and-least-squares/",
    "cleanUrl": "../Library/mathematics/linear-algebra/orthogonality-and-projections/projection-matrices-and-least-squares/",
    "sourcePath": "Library/mathematics/linear-algebra/orthogonality-and-projections/03.projection-matrices-and-least-squares/index.html",
    "publicPath": "Library/mathematics/linear-algebra/orthogonality-and-projections/03.projection-matrices-and-least-squares/",
    "cleanPath": "Library/mathematics/linear-algebra/orthogonality-and-projections/projection-matrices-and-least-squares/",
    "book": "Linear Algebra",
    "bookTitle": "Linear Algebra",
    "bookSlug": "linear-algebra",
    "bookOrder": 999,
    "title": "Projection Matrices and Least Squares",
    "description": "Applying projection matrices to solve unsolvable systems using the method of least squares and the normal equation.",
    "date": "2026-04-18",
    "section": "",
    "chapter": "Orthogonality and Projections",
    "chapterOrder": 3,
    "chapterNumber": "3",
    "lessonorder": 3,
    "lessonNumber": "3",
    "part": " ",
    "tier": "core",
    "keywords": "projections, least squares, linear regression, normal equation, orthogonal, linear algebra",
    "status": "draft",
    "readingTime": 7
  },
  {
    "url": "../Library/mathematics/linear-algebra/orthogonality-and-projections/04.orthogonal-matrices-and-gram-schmidt/",
    "cleanUrl": "../Library/mathematics/linear-algebra/orthogonality-and-projections/orthogonal-matrices-and-gram-schmidt/",
    "sourcePath": "Library/mathematics/linear-algebra/orthogonality-and-projections/04.orthogonal-matrices-and-gram-schmidt/index.html",
    "publicPath": "Library/mathematics/linear-algebra/orthogonality-and-projections/04.orthogonal-matrices-and-gram-schmidt/",
    "cleanPath": "Library/mathematics/linear-algebra/orthogonality-and-projections/orthogonal-matrices-and-gram-schmidt/",
    "book": "Linear Algebra",
    "bookTitle": "Linear Algebra",
    "bookSlug": "linear-algebra",
    "bookOrder": 999,
    "title": "Orthogonal Matrices and Gram-Schmidt",
    "description": "Exploring orthonormal bases, the properties of orthogonal matrices (Q), and constructing them using the Gram-Schmidt process and A = QR factorization.",
    "date": "2026-04-18",
    "section": "",
    "chapter": "Orthogonality and Projections",
    "chapterOrder": 3,
    "chapterNumber": "3",
    "lessonorder": 4,
    "lessonNumber": "4",
    "part": " ",
    "tier": "core",
    "keywords": "orthogonal matrix, orthonormal basis, Gram-Schmidt, QR factorization",
    "status": "draft",
    "readingTime": 7
  },
  {
    "url": "../Library/mathematics/linear-algebra/singular-value-decomposition/01.the-singular-value-decomposition-svd/",
    "cleanUrl": "../Library/mathematics/linear-algebra/singular-value-decomposition/the-singular-value-decomposition-svd/",
    "sourcePath": "Library/mathematics/linear-algebra/singular-value-decomposition/01.the-singular-value-decomposition-svd/index.html",
    "publicPath": "Library/mathematics/linear-algebra/singular-value-decomposition/01.the-singular-value-decomposition-svd/",
    "cleanPath": "Library/mathematics/linear-algebra/singular-value-decomposition/the-singular-value-decomposition-svd/",
    "book": "Linear Algebra",
    "bookTitle": "Linear Algebra",
    "bookSlug": "linear-algebra",
    "bookOrder": 999,
    "title": "The Singular Value Decomposition (SVD)",
    "description": "Exploring the ultimate matrix factorization: decomposing any matrix into orthogonal and diagonal components, connecting the fundamental subspaces, and finding the directions of maximum stretch.",
    "date": "2026-04-18",
    "section": "",
    "chapter": "Singular Value Decomposition",
    "chapterOrder": 6,
    "chapterNumber": "6",
    "lessonorder": 1,
    "lessonNumber": "1",
    "part": " ",
    "tier": "core",
    "keywords": "singular value decomposition, SVD, orthogonal basis, eigenvalues, fundamental subspaces, linear algebra",
    "status": "draft",
    "readingTime": 9
  },
  {
    "url": "../Library/mathematics/linear-algebra/singular-value-decomposition/02.svd-properties/",
    "cleanUrl": "../Library/mathematics/linear-algebra/singular-value-decomposition/svd-properties/",
    "sourcePath": "Library/mathematics/linear-algebra/singular-value-decomposition/02.svd-properties/index.html",
    "publicPath": "Library/mathematics/linear-algebra/singular-value-decomposition/02.svd-properties/",
    "cleanPath": "Library/mathematics/linear-algebra/singular-value-decomposition/svd-properties/",
    "book": "Linear Algebra",
    "bookTitle": "Linear Algebra",
    "bookSlug": "linear-algebra",
    "bookOrder": 999,
    "title": "SVD Properties and Analytical Mechanics",
    "description": "Exploring the analytical mechanics of the SVD: diagonalizing with two bases, the outer product expansion, singular value stability, and numerical realities in LAPACK.",
    "date": "2026-04-25",
    "section": "",
    "chapter": "Singular Value Decomposition",
    "chapterOrder": 6,
    "chapterNumber": "6",
    "lessonorder": 2,
    "lessonNumber": "2",
    "part": " ",
    "tier": "core",
    "keywords": "singular value decomposition, outer product expansion, matrix norms, pseudoinverse, polar decomposition, fundamental subspaces, numerical stability, lapack",
    "status": "draft",
    "readingTime": 10
  },
  {
    "url": "../Library/mathematics/linear-algebra/singular-value-decomposition/03.svd-applications/",
    "cleanUrl": "../Library/mathematics/linear-algebra/singular-value-decomposition/svd-applications/",
    "sourcePath": "Library/mathematics/linear-algebra/singular-value-decomposition/03.svd-applications/index.html",
    "publicPath": "Library/mathematics/linear-algebra/singular-value-decomposition/03.svd-applications/",
    "cleanPath": "Library/mathematics/linear-algebra/singular-value-decomposition/svd-applications/",
    "book": "Linear Algebra",
    "bookTitle": "Linear Algebra",
    "bookSlug": "linear-algebra",
    "bookOrder": 999,
    "title": "Applications of SVD",
    "description": "Moving from theory to practice: applying the SVD to image compression, PCA, eigenfaces, genomics, web search, model reduction, and least-squares optimization.",
    "date": "2026-04-25",
    "section": "",
    "chapter": "Singular Value Decomposition",
    "chapterOrder": 6,
    "chapterNumber": "6",
    "lessonorder": 3,
    "lessonNumber": "3",
    "part": " ",
    "tier": "core",
    "keywords": "singular value decomposition, PCA, principal component analysis, image compression, latent semantic analysis, least squares, eckart-young theorem, eigenfaces, genomics, HITS, POD",
    "status": "draft",
    "readingTime": 10
  },
  {
    "url": "../Library/mathematics/linear-algebra/singular-value-decomposition/04.Image_compression/",
    "cleanUrl": "../Library/mathematics/linear-algebra/singular-value-decomposition/Image_compression/",
    "sourcePath": "Library/mathematics/linear-algebra/singular-value-decomposition/04.Image_compression/index.html",
    "publicPath": "Library/mathematics/linear-algebra/singular-value-decomposition/04.Image_compression/",
    "cleanPath": "Library/mathematics/linear-algebra/singular-value-decomposition/Image_compression/",
    "book": "Linear Algebra",
    "bookTitle": "Linear Algebra",
    "bookSlug": "linear-algebra",
    "bookOrder": 999,
    "title": "SVD for Image Compression",
    "description": "Understanding how the Singular Value Decomposition generalizes symmetric matrix compression to separate, rank, and compress the visual information of an image.",
    "date": "2026-04-26",
    "section": "",
    "chapter": "Singular Value Decomposition",
    "chapterOrder": 6,
    "chapterNumber": "6",
    "lessonorder": 4,
    "lessonNumber": "4",
    "part": " ",
    "tier": "core",
    "keywords": "singular value decomposition, image compression, truncated svd, low-rank approximation, outer product, symmetric matrix",
    "status": "draft",
    "readingTime": 5
  },
  {
    "url": "../Library/mathematics/linear-algebra/solving-linear-systems/01.solving-linear-equations/",
    "cleanUrl": "../Library/mathematics/linear-algebra/solving-linear-systems/solving-linear-equations/",
    "sourcePath": "Library/mathematics/linear-algebra/solving-linear-systems/01.solving-linear-equations/index.html",
    "publicPath": "Library/mathematics/linear-algebra/solving-linear-systems/01.solving-linear-equations/",
    "cleanPath": "Library/mathematics/linear-algebra/solving-linear-systems/solving-linear-equations/",
    "book": "Linear Algebra",
    "bookTitle": "Linear Algebra",
    "bookSlug": "linear-algebra",
    "bookOrder": 999,
    "title": "Solving Linear Equations",
    "description": "How to solve linear equations using Gaussian elimination and matrix factorization",
    "date": "2026-04-04",
    "section": "",
    "chapter": "Solving Linear Systems",
    "chapterOrder": 1,
    "chapterNumber": "1",
    "lessonorder": 1,
    "lessonNumber": "1",
    "part": " ",
    "tier": "core",
    "keywords": "pivot, LU factorization, Gaussian elimination, linear equations, back substitution",
    "status": "draft",
    "readingTime": 8
  },
  {
    "url": "../Library/mathematics/linear-algebra/solving-linear-systems/02.the-complete-solution/",
    "cleanUrl": "../Library/mathematics/linear-algebra/solving-linear-systems/the-complete-solution/",
    "sourcePath": "Library/mathematics/linear-algebra/solving-linear-systems/02.the-complete-solution/index.html",
    "publicPath": "Library/mathematics/linear-algebra/solving-linear-systems/02.the-complete-solution/",
    "cleanPath": "Library/mathematics/linear-algebra/solving-linear-systems/the-complete-solution/",
    "book": "Linear Algebra",
    "bookTitle": "Linear Algebra",
    "bookSlug": "linear-algebra",
    "bookOrder": 999,
    "title": "The Complete Solution",
    "description": "A deep geometric and computational treatment of solving Ax = b using elimination, particular solutions, null spaces, shifted hyperplanes, and rank-based solution classification.",
    "date": "2026-04-11",
    "section": "",
    "chapter": "Solving Linear Systems",
    "chapterOrder": 1,
    "chapterNumber": "1",
    "lessonorder": 2,
    "lessonNumber": "2",
    "part": " ",
    "tier": "core",
    "keywords": "Ax=b, complete solution, particular solution, null space, shifted hyperplane, rank, free variables, linear algebra",
    "status": "draft",
    "readingTime": 6
  },
  {
    "url": "../Library/mathematics/linear-algebra/vector-spaces-and-subspaces/01.the-four-fundamental-subspaces/",
    "cleanUrl": "../Library/mathematics/linear-algebra/vector-spaces-and-subspaces/the-four-fundamental-subspaces/",
    "sourcePath": "Library/mathematics/linear-algebra/vector-spaces-and-subspaces/01.the-four-fundamental-subspaces/index.html",
    "publicPath": "Library/mathematics/linear-algebra/vector-spaces-and-subspaces/01.the-four-fundamental-subspaces/",
    "cleanPath": "Library/mathematics/linear-algebra/vector-spaces-and-subspaces/the-four-fundamental-subspaces/",
    "book": "Linear Algebra",
    "bookTitle": "Linear Algebra",
    "bookSlug": "linear-algebra",
    "bookOrder": 999,
    "title": "The Four Fundamental Subspaces",
    "description": "A comprehensive breakdown of the four fundamental subspaces of a matrix: Row Space, Null Space, Column Space, and Left Null Space, culminating in the Big Picture diagram.",
    "date": "2026-04-17",
    "section": "",
    "chapter": "Vector Spaces and Subspaces",
    "chapterOrder": 2,
    "chapterNumber": "2",
    "lessonorder": 1,
    "lessonNumber": "1",
    "part": " ",
    "tier": "core",
    "keywords": "four subspaces, row space, null space, column space, left null space, fundamental theorem of linear algebra, big picture, strang",
    "status": "live",
    "readingTime": 3
  },
  {
    "url": "../Library/mathematics/linear-algebra/vector-spaces-and-subspaces/02.null-space-from-block-rref/",
    "cleanUrl": "../Library/mathematics/linear-algebra/vector-spaces-and-subspaces/null-space-from-block-rref/",
    "sourcePath": "Library/mathematics/linear-algebra/vector-spaces-and-subspaces/02.null-space-from-block-rref/index.html",
    "publicPath": "Library/mathematics/linear-algebra/vector-spaces-and-subspaces/02.null-space-from-block-rref/",
    "cleanPath": "Library/mathematics/linear-algebra/vector-spaces-and-subspaces/null-space-from-block-rref/",
    "book": "Linear Algebra",
    "bookTitle": "Linear Algebra",
    "bookSlug": "linear-algebra",
    "bookOrder": 999,
    "title": "Null Space from Block RREF",
    "description": "A 4x4 rank 2 matrix example showing how the null space basis appears instantly from the block form [I F] as [-F; I].",
    "date": "2026-04-11",
    "section": "",
    "chapter": "Vector Spaces and Subspaces",
    "chapterOrder": 2,
    "chapterNumber": "2",
    "lessonorder": 2,
    "lessonNumber": "2",
    "part": " ",
    "tier": "core",
    "keywords": "null space, rref, rank 2, block matrix, special solutions, gilbert strang, linear algebra",
    "status": "draft",
    "readingTime": 2
  },
  {
    "url": "../Library/mathematics/linear-algebra/vector-spaces-and-subspaces/03.independence-basis-and-dimension/",
    "cleanUrl": "../Library/mathematics/linear-algebra/vector-spaces-and-subspaces/independence-basis-and-dimension/",
    "sourcePath": "Library/mathematics/linear-algebra/vector-spaces-and-subspaces/03.independence-basis-and-dimension/index.html",
    "publicPath": "Library/mathematics/linear-algebra/vector-spaces-and-subspaces/03.independence-basis-and-dimension/",
    "cleanPath": "Library/mathematics/linear-algebra/vector-spaces-and-subspaces/independence-basis-and-dimension/",
    "book": "Linear Algebra",
    "bookTitle": "Linear Algebra",
    "bookSlug": "linear-algebra",
    "bookOrder": 999,
    "title": "Independence, Basis, and Dimension",
    "description": "linear independence, spanning sets, basis, dimension, rank, and null space, showing how these concepts define the structure of vector spaces.",
    "date": "2026-04-12",
    "section": "",
    "chapter": "Vector Spaces and Subspaces",
    "chapterOrder": 2,
    "chapterNumber": "2",
    "lessonorder": 3,
    "lessonNumber": "3",
    "part": " ",
    "tier": "core",
    "keywords": "linear independence, basis, dimension, vector spaces, spanning sets, null space, column space, rank, pivots, linear algebra",
    "status": "live",
    "readingTime": 14
  },
  {
    "url": "../Library/mathematics/probability-statistics/Hypothesis_test/01. Hypothesis_test/",
    "cleanUrl": "../Library/mathematics/probability-statistics/Hypothesis_test/Hypothesis_test/",
    "sourcePath": "Library/mathematics/probability-statistics/Hypothesis_test/01. Hypothesis_test/index.html",
    "publicPath": "Library/mathematics/probability-statistics/Hypothesis_test/01. Hypothesis_test/",
    "cleanPath": "Library/mathematics/probability-statistics/Hypothesis_test/Hypothesis_test/",
    "book": "Stats",
    "bookTitle": "Stats",
    "bookSlug": "stats",
    "bookOrder": 999,
    "title": "Hypothesis Testing: Z, T, and Chi-Squared Tests",
    "description": "An intuition-first guide to statistical significance, p-values, and choosing the right test.",
    "date": "2026-04-23",
    "section": "",
    "chapter": "Hypothesis Testing",
    "chapterOrder": 6,
    "chapterNumber": "6",
    "lessonorder": 1,
    "lessonNumber": "1",
    "part": "  ",
    "tier": "core",
    "keywords": "hypothesis testing, z-test, t-test, chi-squared, p-value, statistical significance",
    "status": "draft",
    "readingTime": 6
  },
  {
    "url": "../Library/mathematics/probability-statistics/distributions/01.common-probability-distributions/",
    "cleanUrl": "../Library/mathematics/probability-statistics/distributions/common-probability-distributions/",
    "sourcePath": "Library/mathematics/probability-statistics/distributions/01.common-probability-distributions/index.html",
    "publicPath": "Library/mathematics/probability-statistics/distributions/01.common-probability-distributions/",
    "cleanPath": "Library/mathematics/probability-statistics/distributions/common-probability-distributions/",
    "book": "Stats",
    "bookTitle": "Stats",
    "bookSlug": "Stats",
    "bookOrder": 999,
    "title": "Common Probability Distributions",
    "description": "A comprehensive guide to discrete and continuous probability distributions, including PMF, PDF, CDF, means, and variances.",
    "date": "2026-04-10",
    "section": "",
    "chapter": "Distributions",
    "chapterOrder": 2,
    "chapterNumber": "2",
    "lessonorder": 1,
    "lessonNumber": "1",
    "part": " ",
    "tier": "core",
    "keywords": "probability, distributions, statistics, normal distribution, binomial, poisson, exponential, PMF, PDF, CDF",
    "status": "live",
    "readingTime": 4
  },
  {
    "url": "../Library/mathematics/probability-statistics/distributions/02.the-central-limit-theorem-and-maximum-entropy/",
    "cleanUrl": "../Library/mathematics/probability-statistics/distributions/the-central-limit-theorem-and-maximum-entropy/",
    "sourcePath": "Library/mathematics/probability-statistics/distributions/02.the-central-limit-theorem-and-maximum-entropy/index.html",
    "publicPath": "Library/mathematics/probability-statistics/distributions/02.the-central-limit-theorem-and-maximum-entropy/",
    "cleanPath": "Library/mathematics/probability-statistics/distributions/the-central-limit-theorem-and-maximum-entropy/",
    "book": "Stats",
    "bookTitle": "Stats",
    "bookSlug": "Stats",
    "bookOrder": 999,
    "title": "The Central Limit Theorem & Maximum Entropy",
    "description": "A deep dive into the Central Limit Theorem, the origin of the normal distribution equation, and how maximizing entropy leads directly to the Gaussian curve.",
    "date": "2026-04-14",
    "section": "",
    "chapter": "Distributions",
    "chapterOrder": 2,
    "chapterNumber": "2",
    "lessonorder": 2,
    "lessonNumber": "2",
    "part": " ",
    "tier": "core",
    "keywords": "Central Limit Theorem, CLT, Normal Distribution, Gaussian, Maximum Entropy, Probability Density Function, Information Theory",
    "status": "draft",
    "readingTime": 6
  },
  {
    "url": "../Library/mathematics/probability-statistics/foundations-of-probability/01.probability-and-counting/",
    "cleanUrl": "../Library/mathematics/probability-statistics/foundations-of-probability/probability-and-counting/",
    "sourcePath": "Library/mathematics/probability-statistics/foundations-of-probability/01.probability-and-counting/index.html",
    "publicPath": "Library/mathematics/probability-statistics/foundations-of-probability/01.probability-and-counting/",
    "cleanPath": "Library/mathematics/probability-statistics/foundations-of-probability/probability-and-counting/",
    "book": "Stats",
    "bookTitle": "Stats",
    "bookSlug": "Stats",
    "bookOrder": 999,
    "title": "Probability and Counting",
    "description": "A complete foundation of probability axioms, sampling, permutations, combinations, and core counting principles.",
    "date": "2026-04-10",
    "section": "",
    "chapter": "Foundations of Probability",
    "chapterOrder": 1,
    "chapterNumber": "1",
    "lessonorder": 1,
    "lessonNumber": "1",
    "part": " ",
    "tier": "core",
    "keywords": "probability, counting, permutations, combinations, bayes theorem, stars and bars, sample space",
    "status": "live",
    "readingTime": 6
  }
];
